// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywvrogrgdsepbwapsggv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3dnJvZ3JnZHNlcGJ3YXBzZ2d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3ODI5NDUsImV4cCI6MjA2MzM1ODk0NX0.xz0j0L7hl8WoHjqxMqCuKRKp46fvRvbcF9rMaj5aG7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);